create database if not exists test;
DROP TABLE IF EXISTS `PARTS`;
CREATE TABLE `PARTS` (`PART_ID` INT(11) NOT NULL AUTO_INCREMENT , `PART_NAME` TINYTEXT NOT NULL , `PART_IS_NEED` BOOLEAN NOT NULL DEFAULT FALSE , `PART_NUM` INT(11) NOT NULL , PRIMARY KEY (`PART_ID`) ) ENGINE = InnoDB;