
INSERT INTO PARTS(PART_NAME, PART_IS_NEED, PART_NUM) VALUES ('звуковая карта', '0', 2);
INSERT INTO PARTS(PART_NAME, PART_IS_NEED, PART_NUM) VALUES ('процессор', '1', 2);
INSERT INTO PARTS(PART_NAME, PART_IS_NEED, PART_NUM) VALUES ('подсветка корпуса', '0', 0);
INSERT INTO PARTS(PART_NAME, PART_IS_NEED, PART_NUM) VALUES ('HDD диск', '0', 1);
INSERT INTO PARTS(PART_NAME, PART_IS_NEED, PART_NUM) VALUES ('корпус', '1', 10);
INSERT INTO PARTS(PART_NAME, PART_IS_NEED, PART_NUM) VALUES ('память', '1', 10);
INSERT INTO PARTS(PART_NAME, PART_IS_NEED, PART_NUM) VALUES ('SSD диск', '1', 15);
INSERT INTO PARTS(PART_NAME, PART_IS_NEED, PART_NUM) VALUES ('видеокарта', '0', 7);